version: "3.5"
services:
  delivery_management:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/src/app
    command: python3 index.py
    environment:
      - ENV=development
      - PORT=4000
      - MONGO_URL=mongodb://mongo:27017/delivery_management
      - AMQP_URL=amqp://<your-ip>:5672
      - LOCAL_USER=piloto
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27022:27017
