version: "3"
services:
  mongo:
    image: mongo
    ports:
      - "27018:27017"

  customer_management:
    build: .
    command: nodemon start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3001:3000"
    links:
      - mongo
    environment:
      MONGO_URL: mongodb://mongo:27017/customer_management
      AMQP_URL: amqp://192.168.100.113:5672
      NODE_ENV: development
      LOCAL_USER: piloto
    depends_on:
      - mongo
