version: "3"
services:
  order_write:
    build: .
    command: nodemon start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3004:3000"
    links:
      - mongo
    environment:
      MONGO_URL: mongodb://mongo:27017/order_event_store
      AMQP_URL:
      NODE_ENV: development
      LOCAL_USER: piloto
  mongo:
    image: mongo
    ports:
      - "27021:27017"
